# Generated by Django 3.1.7 on 2021-03-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0002_auto_20210310_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='name',
        ),
    ]
